# Generated by Django 5.1.6 on 2025-03-03 22:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='imported',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
