# Generated by Django 5.1.6 on 2025-03-05 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_category_goods_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['-added', '-quantity']},
        ),
        migrations.RemoveIndex(
            model_name='goods',
            name='management__box_f47658_idx',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='box',
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Unit price', max_digits=10),
        ),
        migrations.AlterField(
            model_name='goods',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_provider', to='management.provider'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='goods',
            index=models.Index(fields=['-quantity'], name='management__quantit_23d5c8_idx'),
        ),
    ]
