# Generated by Django 5.1.6 on 2025-03-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_goods_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode/'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
