# Generated by Django 5.1.6 on 2025-03-09 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_goods_qr_code_alter_goods_in_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('state', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-code'],
                'indexes': [models.Index(fields=['-code'], name='management__code_e26304_idx')],
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='goods_city', to='management.storage'),
            preserve_default=False,
        ),
    ]
