# Generated by Django 5.1.6 on 2025-03-10 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_storage_goods_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='goods',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='provider_goods', to='management.goods'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provider',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
