# Generated by Django 5.1.6 on 2025-03-10 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_provider_goods_alter_provider_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_goods', to='management.goods'),
        ),
    ]
