# Generated by Django 5.1.6 on 2025-03-11 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_provider_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MS', 'Missing'), ('SD', 'Send'), ('AD', 'Arrived')], default='AD', max_length=2)),
                ('date_from', models.DateTimeField(blank=True, null=True)),
                ('date_to', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date_from', 'date_to'],
                'indexes': [models.Index(fields=['-date_from'], name='management__date_fr_47f69a_idx'), models.Index(fields=['-date_to'], name='management__date_to_14a11f_idx')],
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_status', to='management.status'),
        ),
    ]
