# Generated by Django 5.1.6 on 2025-03-11 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_status_goods_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='status',
            field=models.ForeignKey(blank=True, default='AD', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_status', to='management.status'),
        ),
    ]
