# Generated by Django 5.1.6 on 2025-03-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_alter_goods_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='status',
        ),
        migrations.AddField(
            model_name='status',
            name='goods',
            field=models.ManyToManyField(related_name='status_goods', to='management.goods'),
        ),
    ]
