# Generated by Django 5.1.6 on 2025-03-11 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_remove_goods_status_status_goods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='goods',
        ),
        migrations.AddField(
            model_name='status',
            name='goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_goods', to='management.goods'),
        ),
    ]
