# Generated by Django 5.1.6 on 2025-03-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_remove_status_goods_status_goods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='goods',
        ),
        migrations.AddField(
            model_name='status',
            name='goods',
            field=models.ManyToManyField(related_name='status_goods', to='management.goods'),
        ),
    ]
