# Generated by Django 5.1.6 on 2025-03-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_worker_user_worker_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
