# Generated by Django 5.1.6 on 2025-03-06 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_manager_city_manager_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='position',
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('worker', 'Worker'), ('manager', 'Manager'), ('chief', 'Chief')], default='worker', max_length=10)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_organisation', to='employees.profile')),
            ],
        ),
        migrations.AddField(
            model_name='worker',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categoty_worker', to='employees.category'),
            preserve_default=False,
        ),
    ]
