# Generated by Django 5.1.6 on 2025-03-09 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_manager_city_alter_manager_code'),
        ('management', '0006_storage_goods_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='city',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='code',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='city',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='code',
        ),
        migrations.AddField(
            model_name='manager',
            name='storage',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='manager_city', to='management.storage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_city', to='management.storage'),
        ),
    ]
