# Generated by Django 5.1.6 on 2025-03-09 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_remove_manager_city_remove_manager_code_and_more'),
        ('management', '0006_storage_goods_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='storage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='worker_city', to='management.storage'),
            preserve_default=False,
        ),
    ]
