# Generated by Django 5.1.6 on 2025-03-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_remove_profile_position_category_worker_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_worker',
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('worker', 'Worker'), ('manager', 'Manager')], default='worker', max_length=10),
        ),
    ]
