# Generated by Django 5.1.6 on 2025-03-06 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_remove_user_is_worker_alter_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categoty_worker', to='employees.category'),
        ),
    ]
