# Generated by Django 5.1.6 on 2025-03-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_worker_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('trainee', 'Trainee'), ('loader', 'Loader'), ('driver', 'Driver'), ('guardian', 'Guardian')], default='worker', max_length=10),
        ),
    ]
