# Generated by Django 5.1.6 on 2025-03-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order',
            field=models.CharField(choices=[('expected', 'Expected'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='expected', max_length=10),
        ),
    ]
