# Generated by Django 5.1.6 on 2025-03-11 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_remove_status_goods_status_goods'),
        ('orders', '0002_alter_order_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='goods',
            field=models.ForeignKey(choices=[('Flour', 'Flour'), ('Shrimp', 'Shrimp'), ('Shrimp', 'Shrimp'), ('Beef Steak', 'Beef Steak'), ('Beef Steak', 'Beef Steak'), ('Makaroni', 'Makaroni'), ('Makaroni', 'Makaroni'), ('Makaroni', 'Makaroni'), ('Rice', 'Rice'), ('Rice', 'Rice'), ('Buckwheat', 'Buckwheat')], on_delete=django.db.models.deletion.CASCADE, related_name='order_goods', to='management.goods'),
        ),
    ]
