# Generated by Django 5.1.6 on 2025-03-11 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_remove_status_goods_status_goods'),
        ('orders', '0006_alter_orderitem_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_goods', to='management.goods'),
        ),
    ]
